package virefs

import (
	"context"
	"errors"
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	v4 "github.com/aws/aws-sdk-go-v2/aws/signer/v4"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/aws/aws-sdk-go-v2/service/s3/types"
	"github.com/aws/smithy-go"
)

// S3API is the subset of *s3.Client that ObjectFS needs.
// Accepting an interface makes unit-testing trivial (no real S3 required).
type S3API interface {
	GetObject(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.Options)) (*s3.GetObjectOutput, error)
	PutObject(ctx context.Context, params *s3.PutObjectInput, optFns ...func(*s3.Options)) (*s3.PutObjectOutput, error)
	DeleteObject(ctx context.Context, params *s3.DeleteObjectInput, optFns ...func(*s3.Options)) (*s3.DeleteObjectOutput, error)
	DeleteObjects(ctx context.Context, params *s3.DeleteObjectsInput, optFns ...func(*s3.Options)) (*s3.DeleteObjectsOutput, error)
	HeadObject(ctx context.Context, params *s3.HeadObjectInput, optFns ...func(*s3.Options)) (*s3.HeadObjectOutput, error)
	ListObjectsV2(ctx context.Context, params *s3.ListObjectsV2Input, optFns ...func(*s3.Options)) (*s3.ListObjectsV2Output, error)
	CopyObject(ctx context.Context, params *s3.CopyObjectInput, optFns ...func(*s3.Options)) (*s3.CopyObjectOutput, error)
}

// PresignAPI is the subset of *s3.PresignClient that ObjectFS needs for
// generating presigned URLs. Accepting an interface keeps tests simple.
type PresignAPI interface {
	PresignGetObject(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error)
	PresignPutObject(ctx context.Context, params *s3.PutObjectInput, optFns ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error)
}

// ObjectOption configures an ObjectFS instance.
type ObjectOption func(*ObjectFS)

// WithPrefix sets a base prefix prepended to every key.
// For example, WithPrefix("uploads/") makes Get(ctx, "a/b.txt") resolve to
// S3 key "uploads/a/b.txt".
func WithPrefix(prefix string) ObjectOption {
	return func(o *ObjectFS) { o.basePrefix = prefix }
}

// WithObjectKeyFunc sets a KeyFunc that transforms every key after CleanKey
// and before the key is combined with the base prefix.
func WithObjectKeyFunc(fn KeyFunc) ObjectOption {
	return func(o *ObjectFS) { o.keyFunc = fn }
}

// WithPresignClient injects a PresignAPI (typically *s3.PresignClient) to
// enable presigned URL generation via the Presigner interface.
func WithPresignClient(pc PresignAPI) ObjectOption {
	return func(o *ObjectFS) { o.presignClient = pc }
}

// WithBaseURL sets the public base URL used by Access when no presign client
// is configured. The URL should include the bucket if needed, e.g.
// "https://my-bucket.s3.us-east-1.amazonaws.com" or
// "https://cdn.example.com".
func WithBaseURL(url string) ObjectOption {
	return func(o *ObjectFS) { o.baseURL = strings.TrimRight(url, "/") }
}

// WithAccessExpires sets the default expiry for presigned URLs generated by
// Access. Default is 15 minutes.
func WithAccessExpires(d time.Duration) ObjectOption {
	return func(o *ObjectFS) { o.accessExpires = d }
}

// WithAccessFunc sets a custom function for Access URL generation.
// The function receives the fully resolved S3 key (after CleanKey + KeyFunc +
// basePrefix) and returns an AccessInfo. This is useful for CDN domains,
// custom URL schemes, or per-file-type routing.
//
// When set, AccessFunc takes priority over presign client and base URL.
func WithAccessFunc(fn AccessFunc) ObjectOption {
	return func(o *ObjectFS) { o.accessFunc = fn }
}

// ObjectFS implements FS backed by an S3-compatible object store.
// It also implements the optional Presigner interface when a PresignAPI client
// is provided via WithPresignClient.
type ObjectFS struct {
	client        S3API
	bucket        string
	basePrefix    string
	keyFunc       KeyFunc
	presignClient PresignAPI
	baseURL       string
	accessExpires time.Duration
	accessFunc    AccessFunc
}

const defaultAccessExpires = 15 * time.Minute

// NewObjectFS creates an ObjectFS targeting the given bucket.
//
// Use WithPrefix to add a key prefix. To use a custom endpoint (MinIO, Ceph,
// R2, ...) configure the *s3.Client before passing it in:
//
//	client := s3.NewFromConfig(cfg, func(o *s3.Options) {
//	    o.BaseEndpoint = aws.String("https://s3.example.com")
//	    o.UsePathStyle = true
//	})
//	fs := NewObjectFS(client, "my-bucket", WithPrefix("data/"))
func NewObjectFS(client S3API, bucket string, opts ...ObjectOption) *ObjectFS {
	o := &ObjectFS{
		client: client,
		bucket: bucket,
	}
	for _, fn := range opts {
		fn(o)
	}
	return o
}

// s3Key prepends basePrefix and cleans the key.
func (o *ObjectFS) s3Key(key string) (string, error) {
	cleaned, err := CleanKey(key)
	if err != nil {
		return "", err
	}
	if o.keyFunc != nil {
		cleaned = o.keyFunc(cleaned)
	}
	return o.basePrefix + cleaned, nil
}

// Get implements FS.
func (o *ObjectFS) Get(ctx context.Context, key string) (io.ReadCloser, error) {
	s3k, err := o.s3Key(key)
	if err != nil {
		return nil, &OpError{Op: "Get", Key: key, Err: err}
	}
	out, err := o.client.GetObject(ctx, &s3.GetObjectInput{
		Bucket: aws.String(o.bucket),
		Key:    aws.String(s3k),
	})
	if err != nil {
		return nil, &OpError{Op: "Get", Key: key, Err: mapS3Error(err)}
	}
	return out.Body, nil
}

// Put implements FS.
func (o *ObjectFS) Put(ctx context.Context, key string, r io.Reader, opts ...PutOption) error {
	s3k, err := o.s3Key(key)
	if err != nil {
		return &OpError{Op: "Put", Key: key, Err: err}
	}
	cfg := BuildPutConfig(opts)
	input := &s3.PutObjectInput{
		Bucket: aws.String(o.bucket),
		Key:    aws.String(s3k),
		Body:   r,
	}
	if cfg.ContentType != "" {
		input.ContentType = aws.String(cfg.ContentType)
	}
	if len(cfg.Metadata) > 0 {
		input.Metadata = cfg.Metadata
	}
	_, err = o.client.PutObject(ctx, input)
	if err != nil {
		return &OpError{Op: "Put", Key: key, Err: mapS3Error(err)}
	}
	return nil
}

// Delete implements FS.
func (o *ObjectFS) Delete(ctx context.Context, key string) error {
	s3k, err := o.s3Key(key)
	if err != nil {
		return &OpError{Op: "Delete", Key: key, Err: err}
	}
	_, err = o.client.DeleteObject(ctx, &s3.DeleteObjectInput{
		Bucket: aws.String(o.bucket),
		Key:    aws.String(s3k),
	})
	if err != nil {
		return &OpError{Op: "Delete", Key: key, Err: mapS3Error(err)}
	}
	return nil
}

// List implements FS.
func (o *ObjectFS) List(ctx context.Context, prefix string) (*ListResult, error) {
	cleanedPrefix, err := CleanKey(prefix)
	if err != nil {
		return nil, &OpError{Op: "List", Key: prefix, Err: err}
	}
	s3Prefix := o.basePrefix + cleanedPrefix
	if s3Prefix != "" && s3Prefix[len(s3Prefix)-1] != '/' {
		s3Prefix += "/"
	}

	delimiter := "/"
	result := &ListResult{}
	var continuationToken *string
	for {
		if err := ctx.Err(); err != nil {
			return nil, &OpError{Op: "List", Key: prefix, Err: err}
		}
		out, err := o.client.ListObjectsV2(ctx, &s3.ListObjectsV2Input{
			Bucket:            aws.String(o.bucket),
			Prefix:            aws.String(s3Prefix),
			Delimiter:         aws.String(delimiter),
			ContinuationToken: continuationToken,
		})
		if err != nil {
			return nil, &OpError{Op: "List", Key: prefix, Err: mapS3Error(err)}
		}
		for _, obj := range out.Contents {
			k := aws.ToString(obj.Key)
			if len(k) > len(o.basePrefix) {
				k = k[len(o.basePrefix):]
			}
			result.Files = append(result.Files, FileInfo{
				Key:          k,
				Size:         aws.ToInt64(obj.Size),
				LastModified: aws.ToTime(obj.LastModified),
			})
		}
		for _, cp := range out.CommonPrefixes {
			k := aws.ToString(cp.Prefix)
			if len(k) > len(o.basePrefix) {
				k = k[len(o.basePrefix):]
			}
			k = strings.TrimSuffix(k, "/")
			result.Files = append(result.Files, FileInfo{
				Key:   k,
				IsDir: true,
			})
		}
		if !aws.ToBool(out.IsTruncated) {
			break
		}
		continuationToken = out.NextContinuationToken
	}
	return result, nil
}

// Stat implements FS.
func (o *ObjectFS) Stat(ctx context.Context, key string) (*FileInfo, error) {
	s3k, err := o.s3Key(key)
	if err != nil {
		return nil, &OpError{Op: "Stat", Key: key, Err: err}
	}
	out, err := o.client.HeadObject(ctx, &s3.HeadObjectInput{
		Bucket: aws.String(o.bucket),
		Key:    aws.String(s3k),
	})
	if err != nil {
		return nil, &OpError{Op: "Stat", Key: key, Err: mapS3Error(err)}
	}
	return &FileInfo{
		Key:          key,
		Size:         aws.ToInt64(out.ContentLength),
		LastModified: aws.ToTime(out.LastModified),
		ContentType:  aws.ToString(out.ContentType),
	}, nil
}

// Exists implements FS.
func (o *ObjectFS) Exists(ctx context.Context, key string) (bool, error) {
	s3k, err := o.s3Key(key)
	if err != nil {
		return false, &OpError{Op: "Exists", Key: key, Err: err}
	}
	_, err = o.client.HeadObject(ctx, &s3.HeadObjectInput{
		Bucket: aws.String(o.bucket),
		Key:    aws.String(s3k),
	})
	if err == nil {
		return true, nil
	}
	if errors.Is(mapS3Error(err), ErrNotFound) {
		return false, nil
	}
	return false, &OpError{Op: "Exists", Key: key, Err: mapS3Error(err)}
}

// PresignGet returns a presigned GET URL for the given key.
// Requires WithPresignClient to have been set; returns ErrNotSupported otherwise.
func (o *ObjectFS) PresignGet(ctx context.Context, key string, expires time.Duration) (*PresignedRequest, error) {
	if o.presignClient == nil {
		return nil, &OpError{Op: "PresignGet", Key: key, Err: fmt.Errorf("%w: presign client not configured", ErrNotSupported)}
	}
	s3k, err := o.s3Key(key)
	if err != nil {
		return nil, &OpError{Op: "PresignGet", Key: key, Err: err}
	}
	req, err := o.presignClient.PresignGetObject(ctx, &s3.GetObjectInput{
		Bucket: aws.String(o.bucket),
		Key:    aws.String(s3k),
	}, func(opts *s3.PresignOptions) {
		opts.Expires = expires
	})
	if err != nil {
		return nil, &OpError{Op: "PresignGet", Key: key, Err: err}
	}
	return &PresignedRequest{
		URL:    req.URL,
		Method: req.Method,
		Header: req.SignedHeader,
	}, nil
}

// PresignPut returns a presigned PUT URL for the given key.
// Requires WithPresignClient to have been set; returns ErrNotSupported otherwise.
func (o *ObjectFS) PresignPut(ctx context.Context, key string, expires time.Duration) (*PresignedRequest, error) {
	if o.presignClient == nil {
		return nil, &OpError{Op: "PresignPut", Key: key, Err: fmt.Errorf("%w: presign client not configured", ErrNotSupported)}
	}
	s3k, err := o.s3Key(key)
	if err != nil {
		return nil, &OpError{Op: "PresignPut", Key: key, Err: err}
	}
	req, err := o.presignClient.PresignPutObject(ctx, &s3.PutObjectInput{
		Bucket: aws.String(o.bucket),
		Key:    aws.String(s3k),
	}, func(opts *s3.PresignOptions) {
		opts.Expires = expires
	})
	if err != nil {
		return nil, &OpError{Op: "PresignPut", Key: key, Err: err}
	}
	return &PresignedRequest{
		URL:    req.URL,
		Method: req.Method,
		Header: req.SignedHeader,
	}, nil
}

// Access returns an AccessInfo for the given key.
// Priority: AccessFunc > PresignClient > BaseURL > ErrNotSupported.
func (o *ObjectFS) Access(ctx context.Context, key string) (*AccessInfo, error) {
	s3k, err := o.s3Key(key)
	if err != nil {
		return nil, &OpError{Op: "Access", Key: key, Err: err}
	}

	if o.accessFunc != nil {
		if info := o.accessFunc(s3k); info != nil {
			return info, nil
		}
	}

	if o.presignClient != nil {
		expires := o.accessExpires
		if expires == 0 {
			expires = defaultAccessExpires
		}
		req, err := o.presignClient.PresignGetObject(ctx, &s3.GetObjectInput{
			Bucket: aws.String(o.bucket),
			Key:    aws.String(s3k),
		}, func(opts *s3.PresignOptions) {
			opts.Expires = expires
		})
		if err != nil {
			return nil, &OpError{Op: "Access", Key: key, Err: err}
		}
		return &AccessInfo{URL: req.URL}, nil
	}

	if o.baseURL != "" {
		return &AccessInfo{URL: o.baseURL + "/" + s3k}, nil
	}

	return nil, &OpError{Op: "Access", Key: key, Err: fmt.Errorf("%w: set WithAccessFunc, WithPresignClient, or WithBaseURL", ErrNotSupported)}
}

// Copy implements Copier using S3 CopyObject for efficient same-bucket copies.
func (o *ObjectFS) Copy(ctx context.Context, srcKey, dstKey string) error {
	srcS3k, err := o.s3Key(srcKey)
	if err != nil {
		return &OpError{Op: "Copy", Key: srcKey, Err: err}
	}
	dstS3k, err := o.s3Key(dstKey)
	if err != nil {
		return &OpError{Op: "Copy", Key: dstKey, Err: err}
	}
	_, err = o.client.CopyObject(ctx, &s3.CopyObjectInput{
		Bucket:     aws.String(o.bucket),
		CopySource: aws.String(o.bucket + "/" + srcS3k),
		Key:        aws.String(dstS3k),
	})
	if err != nil {
		return &OpError{Op: "Copy", Key: srcKey + " -> " + dstKey, Err: mapS3Error(err)}
	}
	return nil
}

// BatchDelete implements BatchDeleter using S3 DeleteObjects for efficient
// bulk deletion of up to 1000 keys per call.
func (o *ObjectFS) BatchDelete(ctx context.Context, keys []string) error {
	const maxBatch = 1000
	for i := 0; i < len(keys); i += maxBatch {
		if err := ctx.Err(); err != nil {
			return &OpError{Op: "BatchDelete", Key: fmt.Sprintf("%d keys remaining", len(keys)-i), Err: err}
		}
		end := i + maxBatch
		if end > len(keys) {
			end = len(keys)
		}
		objects := make([]types.ObjectIdentifier, 0, end-i)
		for _, key := range keys[i:end] {
			s3k, err := o.s3Key(key)
			if err != nil {
				return &OpError{Op: "BatchDelete", Key: key, Err: err}
			}
			objects = append(objects, types.ObjectIdentifier{Key: aws.String(s3k)})
		}
		out, err := o.client.DeleteObjects(ctx, &s3.DeleteObjectsInput{
			Bucket: aws.String(o.bucket),
			Delete: &types.Delete{Objects: objects, Quiet: aws.Bool(true)},
		})
		if err != nil {
			return &OpError{Op: "BatchDelete", Key: fmt.Sprintf("%d keys", end-i), Err: mapS3Error(err)}
		}
		if len(out.Errors) > 0 {
			e := out.Errors[0]
			return &OpError{
				Op:  "BatchDelete",
				Key: aws.ToString(e.Key),
				Err: fmt.Errorf("s3 error %s: %s", aws.ToString(e.Code), aws.ToString(e.Message)),
			}
		}
	}
	return nil
}

// Compile-time checks.
var (
	_ FS           = (*ObjectFS)(nil)
	_ Presigner    = (*ObjectFS)(nil)
	_ Copier       = (*ObjectFS)(nil)
	_ BatchDeleter = (*ObjectFS)(nil)
)

// mapS3Error converts common S3 error types to virefs sentinel errors.
func mapS3Error(err error) error {
	var nsk *types.NoSuchKey
	if errors.As(err, &nsk) {
		return ErrNotFound
	}
	var nf *types.NotFound
	if errors.As(err, &nf) {
		return ErrNotFound
	}
	var apiErr smithy.APIError
	if errors.As(err, &apiErr) {
		if apiErr.ErrorCode() == "NotFound" || apiErr.ErrorCode() == "NoSuchKey" {
			return ErrNotFound
		}
	}
	return err
}
